### ISSUE TITLE
4Hr Testing lastnight.

### ISSUE THREAD

**Issue by DatGoose** [Eternita-S/DSREyeLocator#1]
Hey I thought I would drop a message.

I did 4hrs lastnight using this,, it worked flawlessly at death of the heavens but at sanctity of the ward there were a few eye/thordan placements where it couldn't identify. I don't screen record in a method that would allow me to easily identify a pull to seprate my logs that I'd be able to provide you them with an clarity of which pull there were problems.

Zero crashes in my session, cheers to that. Would have sucked to have a crash at death but figured it was worth in the name of science and possibly providing feed back.

Thanks for this, it was a real treat at not having to second guess my placement :).

**Comment by Limiana** [comment]
@DatGoose thanks for testing, one of the unknown positions already got added in new version, I don't really know if there are more positions, but I think shouldn't be
You can give me your act log if you have it, it would have necessary information if chat logging was enabled in act's settings
(you can delete/replace players names, I don't need them)
> it worked flawlessly at death of the heavens

you just didn't got eye at a position that was unknown :) and it was unknown because I didn't got it in my raid session where I collected that data too

**Comment by DatGoose** [comment]
File is too large to upload to git so here is a link to it from my drive.

https://drive.google.com/file/d/1-8770OoxcQFt_-NP6Q7-UQ9wIV4j3RRb/view?usp=sharing

I culled out the names and removed everything before we entered and after we ended our 2nd lock out. I hope this helps :)

**Comment by Limiana** [comment]
Yes, new version should now have the position that was missing
